### ISSUE TITLE
Utils naming conflict with GeNa

### ISSUE THREAD

**Issue by goldfire** [Roland09/VegetationStudioProExtensions#2]
I tried installing this in a project that has GeNa installed and I started getting the following error:

```
'Utils' does not contain a definition for 'GetFrapoch'
```

It seems that something in this package is causing a namespace conflict, which likely affects more than just GeNa, but that is all I was able to test it on.

**Comment by Roland09** [comment]
Oops, sorry, the Utils class didn't have a namespace. It's fixed now.

Thanks for reporting!

**Comment by goldfire** [comment]
Awesome, thanks for the quick fix!
